version: 0.0
os: linux
files:
  - source: /recipes
    destination: /var/recipes
hooks:
  BeforeInstall:
    - location: scripts/install_environment
      timeout: 60000
      runas: root
    - location: scripts/start_server
      timeout: 2000
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 2000
      runas: root
