#!/bin/bash

yum install python3
pip3 install -r requirements.txt

aws s3api get-object --bucket cookwithculi-appdata --key db_password .db_password
aws s3api get-object --bucket cookwithculi-appdata --key db_uri .db_uri
