#!/bin/bash

if curl -s localhost:6969/ | grep "Hello World" > /dev/null
then
	echo "Server already running"
else
	echo "Starting up server"
	python3 graph.py 6969 &
	jobs -l
	disown -h %1
	jobs -l
fi
