#!/bin/bash

echo "Attempting to stop server by terminating."
export server_process=$(ps aux | grep "[p]ython3 graph.py" | awk '{print $2}')
if [ ${#server_process} -gt 0 ]
then
  kill -SIGTERM $(ps aux | grep "[p]ython3 graph.py" | awk '{print $2}')
  echo "Sent termination signal to the server."
else
	echo "Server is not running"
fi
